name: New Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions:
      packages: write
      contents: write
    uses: compliance-framework/workflows/.github/workflows/plugin-release.yml@main
